### ISSUE TITLE
Start Working on Idle State for Charger

### ISSUE THREAD

**Issue by MarioVquero** [StudioAspen/Aspen2024-2025#24]
Just need to Start working or finish on the idle state and optionally the Dazed State

- [ ] Get Idle State to work
- [ ] (Optional) Dazed State

if you have any questions feel free to message the group thread

**Comment by johnzhou1210** [comment]
https://github.com/StudioAspen/Aspen2024-2025/pull/41

**Comment by johnzhou1210** [comment]
https://github.com/StudioAspen/Aspen2024-2025/compare/development...John-Charger-Idle-2
