### ISSUE TITLE
Chaining System

### ISSUE THREAD

**Issue by BenicioLadines** [StudioAspen/Aspen2024-2025#32]
You attack an enemy over and over to keep them in hitstun, and a number goes up!

not sure what it'll do yet but like the momentum system, you'll get less and less time to keep ur number going up and when the timer hits 0 some kinda bonus will be applied

**Comment by samsonahh** [comment]
Apply the same system as #31. Refer to the task breakdown.


- [ ] Add an additional function `private void ApplyCombo()`: This runs once the timer hits zero
- Leave it empty for now (may change into public UnityEvent)
